"""initial schema

Revision ID: 1f5b0d9c44a3
Revises:
Create Date: 2026-08-11 18:52:50.420944

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1f5b0d9c44a3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_table(
        "events",
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "tx_id",
            sa.BigInteger(),
            server_default=sa.text("pg_current_xact_id()::text::bigint"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("correlation_id", sa.Text(), nullable=False),
        sa.Column("causation_id", sa.Text(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_events_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("sequence", name=op.f("pk_events")),
        sa.UniqueConstraint("id", name="uq_events_id"),
    )
    op.create_index(
        "ix_events_entity", "events", ["tenant_id", "entity_type", "entity_id"], unique=False
    )
    op.create_index("ix_events_tenant_sequence", "events", ["tenant_id", "sequence"], unique=False)
    op.create_table(
        "principals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "kind IN ('human', 'agent', 'service')", name=op.f("ck_principals_kind")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'disabled')", name=op.f("ck_principals_status")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_principals_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_principals")),
    )
    op.create_index(
        "ix_principals_tenant_created",
        "principals",
        ["tenant_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "task_counters",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("last_value", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_task_counters_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_task_counters")),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("principal_id", sa.UUID(), nullable=False),
        sa.Column("key_prefix", sa.Text(), nullable=False),
        sa.Column("key_hash", sa.Text(), nullable=False),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_used_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("revoked_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"], ["principals.id"], name=op.f("fk_api_keys_principal_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_api_keys_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_api_keys_key_hash")),
        sa.UniqueConstraint("key_prefix", name=op.f("uq_api_keys_key_prefix")),
    )
    op.create_table(
        "delegations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("human_principal_id", sa.UUID(), nullable=False),
        sa.Column("agent_principal_id", sa.UUID(), nullable=False),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("starts_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("revoked_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_principal_id"],
            ["principals.id"],
            name=op.f("fk_delegations_agent_principal_id_principals"),
        ),
        sa.ForeignKeyConstraint(
            ["human_principal_id"],
            ["principals.id"],
            name=op.f("fk_delegations_human_principal_id_principals"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_delegations_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delegations")),
    )
    op.create_index(
        "ix_delegations_tenant_agent",
        "delegations",
        ["tenant_id", "agent_principal_id"],
        unique=False,
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("principal_id", sa.UUID(), nullable=False),
        sa.Column("request_method", sa.Text(), nullable=False),
        sa.Column("request_path", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
            name=op.f("fk_idempotency_keys_principal_id_principals"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_idempotency_keys_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("tenant_id", "key", name=op.f("pk_idempotency_keys")),
    )
    op.create_index("ix_idempotency_expires", "idempotency_keys", ["expires_at"], unique=False)
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("available_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("locked_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("locked_by", sa.Text(), nullable=True),
        sa.Column("delivered_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_outbox_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_outbox_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox")),
    )
    op.create_index(
        "ix_outbox_undelivered",
        "outbox",
        ["available_at"],
        unique=False,
        postgresql_where=sa.text("delivered_at IS NULL"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("public_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("priority", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("claim_epoch", sa.BigInteger(), nullable=False),
        sa.Column("active_claim_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "priority IN ('critical', 'high', 'medium', 'low')", name=op.f("ck_tasks_priority")
        ),
        sa.CheckConstraint(
            "status IN ('backlog', 'todo', 'in_progress', 'blocked', 'done', 'cancelled')",
            name=op.f("ck_tasks_status"),
        ),
        sa.CheckConstraint("claim_epoch >= 0", name=op.f("ck_tasks_claim_epoch_nonnegative")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_tasks_version_positive")),
        sa.ForeignKeyConstraint(
            ["assignee_id"], ["principals.id"], name=op.f("fk_tasks_assignee_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["principals.id"], name=op.f("fk_tasks_created_by_principals")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["principals.id"], name=op.f("fk_tasks_owner_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_tasks_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("tenant_id", "public_id", name="uq_tasks_tenant_public_id"),
    )
    op.create_index(
        "ix_tasks_tenant_created", "tasks", ["tenant_id", "created_at", "id"], unique=False
    )
    op.create_index("ix_tasks_tenant_status", "tasks", ["tenant_id", "status"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("principal_id", sa.UUID(), nullable=False),
        sa.Column("on_behalf_of_id", sa.UUID(), nullable=True),
        sa.Column("delegation_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("client_name", sa.Text(), nullable=False),
        sa.Column("client_version", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("heartbeat_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("ended_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'stale', 'closed')", name=op.f("ck_sessions_status")
        ),
        sa.ForeignKeyConstraint(
            ["delegation_id"],
            ["delegations.id"],
            name=op.f("fk_sessions_delegation_id_delegations"),
        ),
        sa.ForeignKeyConstraint(
            ["on_behalf_of_id"],
            ["principals.id"],
            name=op.f("fk_sessions_on_behalf_of_id_principals"),
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"], ["principals.id"], name=op.f("fk_sessions_principal_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sessions_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(
        "ix_sessions_active_expires",
        "sessions",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "ix_sessions_tenant_created", "sessions", ["tenant_id", "started_at", "id"], unique=False
    )
    op.create_index("ix_sessions_tenant_status", "sessions", ["tenant_id", "status"], unique=False)
    op.create_table(
        "task_claims",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("holder_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("acquired_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("heartbeat_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("released_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("release_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'released', 'stale')", name=op.f("ck_task_claims_status")
        ),
        sa.ForeignKeyConstraint(
            ["holder_id"], ["principals.id"], name=op.f("fk_task_claims_holder_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_task_claims_session_id_sessions")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_task_claims_task_id_tasks")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_task_claims_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_claims")),
        sa.UniqueConstraint("task_id", "fencing_token", name="uq_task_claims_task_fencing"),
    )
    op.create_index(
        "ix_task_claims_active_expires",
        "task_claims",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index("ix_task_claims_session", "task_claims", ["session_id"], unique=False)
    op.create_index(
        "ix_task_claims_tenant_created",
        "task_claims",
        ["tenant_id", "acquired_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_task_claims_one_active_per_task",
        "task_claims",
        ["task_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )

    # Circular FK tasks -> task_claims, added after both tables exist.
    op.create_foreign_key(
        "fk_tasks_active_claim", "tasks", "task_claims", ["active_claim_id"], ["id"]
    )

    # The event journal is append-only: reject UPDATE/DELETE at the DB level,
    # regardless of which role the application connects as.
    op.execute(
        """
        CREATE FUNCTION forbid_event_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'events are append-only (% on events is forbidden)', TG_OP
                USING ERRCODE = 'raise_exception';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER events_append_only
        BEFORE UPDATE OR DELETE ON events
        FOR EACH ROW EXECUTE FUNCTION forbid_event_mutation();
        """
    )
    op.execute(
        """
        CREATE TRIGGER events_append_only_truncate
        BEFORE TRUNCATE ON events
        FOR EACH STATEMENT EXECUTE FUNCTION forbid_event_mutation();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER events_append_only_truncate ON events")
    op.execute("DROP TRIGGER events_append_only ON events")
    op.execute("DROP FUNCTION forbid_event_mutation()")
    op.drop_constraint("fk_tasks_active_claim", "tasks", type_="foreignkey")
    op.drop_index(
        "uq_task_claims_one_active_per_task",
        table_name="task_claims",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_task_claims_tenant_created", table_name="task_claims")
    op.drop_index("ix_task_claims_session", table_name="task_claims")
    op.drop_index(
        "ix_task_claims_active_expires",
        table_name="task_claims",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("task_claims")
    op.drop_index("ix_sessions_tenant_status", table_name="sessions")
    op.drop_index("ix_sessions_tenant_created", table_name="sessions")
    op.drop_index(
        "ix_sessions_active_expires",
        table_name="sessions",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("sessions")
    op.drop_index("ix_tasks_tenant_status", table_name="tasks")
    op.drop_index("ix_tasks_tenant_created", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(
        "ix_outbox_undelivered",
        table_name="outbox",
        postgresql_where=sa.text("delivered_at IS NULL"),
    )
    op.drop_table("outbox")
    op.drop_index("ix_idempotency_expires", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_delegations_tenant_agent", table_name="delegations")
    op.drop_table("delegations")
    op.drop_table("api_keys")
    op.drop_table("task_counters")
    op.drop_index("ix_principals_tenant_created", table_name="principals")
    op.drop_table("principals")
    op.drop_index("ix_events_tenant_sequence", table_name="events")
    op.drop_index("ix_events_entity", table_name="events")
    op.drop_table("events")
    op.drop_table("tenants")
    # ### end Alembic commands ###
