"""organization model

Revision ID: fc01bd83300c
Revises: 1f5b0d9c44a3
Create Date: 2026-08-11 20:43:49.378243

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "fc01bd83300c"
down_revision: str | None = "1f5b0d9c44a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capabilities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_capabilities_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capabilities")),
        sa.UniqueConstraint("tenant_id", "name", name="uq_capabilities_tenant_name"),
    )
    op.create_index(
        "ix_capabilities_tenant_created",
        "capabilities",
        ["tenant_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("protocol", sa.Text(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "protocol IN ('mcp', 'http', 'local', 'opencode', 'custom')",
            name=op.f("ck_skills_protocol"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'deprecated', 'disabled')", name=op.f("ck_skills_status")
        ),
        sa.CheckConstraint("row_version >= 1", name=op.f("ck_skills_row_version_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_skills_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
        sa.UniqueConstraint("tenant_id", "name", "version", name="uq_skills_tenant_name_version"),
    )
    op.create_index(
        "ix_skills_tenant_created", "skills", ["tenant_id", "created_at", "id"], unique=False
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active', 'archived')", name=op.f("ck_workspaces_status")),
        sa.CheckConstraint("id != parent_id", name=op.f("ck_workspaces_not_own_parent")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_workspaces_version_positive")),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["workspaces.id"], name=op.f("fk_workspaces_parent_id_workspaces")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_workspaces_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
        sa.UniqueConstraint("tenant_id", "id", name="uq_workspaces_tenant_id_id"),
    )
    op.create_index(
        "ix_workspaces_tenant_created",
        "workspaces",
        ["tenant_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_workspaces_tenant_parent", "workspaces", ["tenant_id", "parent_id"], unique=False
    )
    op.create_index(
        "uq_workspaces_root_slug",
        "workspaces",
        ["tenant_id", "slug"],
        unique=True,
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.create_index(
        "uq_workspaces_sibling_slug",
        "workspaces",
        ["tenant_id", "parent_id", "slug"],
        unique=True,
        postgresql_where=sa.text("parent_id IS NOT NULL"),
    )

    # tasks join the organization model (moved up: task_relations' composite
    # FKs require uq_tasks_tenant_id_id to exist before that table is created).
    op.add_column("tasks", sa.Column("workspace_id", sa.UUID(), nullable=True))
    op.create_index("ix_tasks_workspace", "tasks", ["workspace_id"], unique=False)
    op.create_unique_constraint("uq_tasks_tenant_id_id", "tasks", ["tenant_id", "id"])
    op.create_foreign_key(
        op.f("fk_tasks_workspace_id_workspaces"), "tasks", "workspaces", ["workspace_id"], ["id"]
    )
    op.create_table(
        "principal_capabilities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("principal_id", sa.UUID(), nullable=False),
        sa.Column("capability_id", sa.UUID(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["capabilities.id"],
            name=op.f("fk_principal_capabilities_capability_id_capabilities"),
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
            name=op.f("fk_principal_capabilities_principal_id_principals"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_principal_capabilities_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_principal_capabilities")),
        sa.UniqueConstraint("principal_id", "capability_id", name="uq_principal_capabilities_pair"),
    )
    op.create_index(
        "ix_principal_capabilities_capability",
        "principal_capabilities",
        ["capability_id"],
        unique=False,
    )
    op.create_table(
        "principal_skills",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("principal_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
            name=op.f("fk_principal_skills_principal_id_principals"),
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skills.id"], name=op.f("fk_principal_skills_skill_id_skills")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_principal_skills_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_principal_skills")),
        sa.UniqueConstraint("principal_id", "skill_id", name="uq_principal_skills_pair"),
    )
    op.create_index("ix_principal_skills_skill", "principal_skills", ["skill_id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_roles_version_positive")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_roles_tenant_id_tenants")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], name=op.f("fk_roles_workspace_id_workspaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.create_index(
        "ix_roles_tenant_created", "roles", ["tenant_id", "created_at", "id"], unique=False
    )
    op.create_index(
        "uq_roles_global_slug",
        "roles",
        ["tenant_id", "slug"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NULL"),
    )
    op.create_index(
        "uq_roles_workspace_slug",
        "roles",
        ["tenant_id", "workspace_id", "slug"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NOT NULL"),
    )
    op.create_table(
        "workspace_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("principal_id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
            name=op.f("fk_workspace_members_principal_id_principals"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_workspace_members_tenant_id_tenants")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workspace_members_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_members")),
        sa.UniqueConstraint("workspace_id", "principal_id", name="uq_workspace_members_pair"),
    )
    op.create_index(
        "ix_workspace_members_principal", "workspace_members", ["principal_id"], unique=False
    )
    op.create_table(
        "principal_roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("principal_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["principals.id"],
            name=op.f("fk_principal_roles_principal_id_principals"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_principal_roles_role_id_roles")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_principal_roles_tenant_id_tenants")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_principal_roles_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_principal_roles")),
    )
    op.create_index(
        "ix_principal_roles_principal", "principal_roles", ["principal_id"], unique=False
    )
    op.create_index("ix_principal_roles_role", "principal_roles", ["role_id"], unique=False)
    op.create_index(
        "uq_principal_roles_global",
        "principal_roles",
        ["principal_id", "role_id"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NULL"),
    )
    op.create_index(
        "uq_principal_roles_scoped",
        "principal_roles",
        ["principal_id", "role_id", "workspace_id"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NOT NULL"),
    )
    op.create_table(
        "task_relations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("from_task_id", sa.UUID(), nullable=False),
        sa.Column("to_task_id", sa.UUID(), nullable=False),
        sa.Column("relation_type", sa.Text(), nullable=False),
        sa.Column("created_by_principal_id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "relation_type IN ('parent', 'blocks', 'depends_on', 'spawned_by', 'related_to')",
            name=op.f("ck_task_relations_relation_type"),
        ),
        sa.CheckConstraint("from_task_id != to_task_id", name=op.f("ck_task_relations_not_self")),
        sa.ForeignKeyConstraint(
            ["created_by_principal_id"],
            ["principals.id"],
            name=op.f("fk_task_relations_created_by_principal_id_principals"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "from_task_id"],
            ["tasks.tenant_id", "tasks.id"],
            name="fk_task_relations_from_task",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "to_task_id"],
            ["tasks.tenant_id", "tasks.id"],
            name="fk_task_relations_to_task",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_task_relations_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_relations")),
        sa.UniqueConstraint(
            "from_task_id", "to_task_id", "relation_type", name="uq_task_relations_edge"
        ),
    )
    op.create_index("ix_task_relations_from", "task_relations", ["from_task_id"], unique=False)
    op.create_index("ix_task_relations_to", "task_relations", ["to_task_id"], unique=False)
    op.create_table(
        "task_requirements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=True),
        sa.Column("capability_id", sa.UUID(), nullable=True),
        sa.Column("skill_id", sa.UUID(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(kind = 'role' AND role_id IS NOT NULL "
            " AND capability_id IS NULL AND skill_id IS NULL) OR "
            "(kind = 'capability' AND capability_id IS NOT NULL "
            " AND role_id IS NULL AND skill_id IS NULL) OR "
            "(kind = 'skill' AND skill_id IS NOT NULL "
            " AND role_id IS NULL AND capability_id IS NULL)",
            name=op.f("ck_task_requirements_exactly_one_ref"),
        ),
        sa.CheckConstraint(
            "kind IN ('role', 'capability', 'skill')", name=op.f("ck_task_requirements_kind")
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["capabilities.id"],
            name=op.f("fk_task_requirements_capability_id_capabilities"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_task_requirements_role_id_roles")
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skills.id"], name=op.f("fk_task_requirements_skill_id_skills")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_task_requirements_task_id_tasks")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_task_requirements_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_requirements")),
    )
    op.create_index("ix_task_requirements_task", "task_requirements", ["task_id"], unique=False)
    op.create_index(
        "uq_task_requirements_capability",
        "task_requirements",
        ["task_id", "capability_id"],
        unique=True,
        postgresql_where=sa.text("capability_id IS NOT NULL"),
    )
    op.create_index(
        "uq_task_requirements_role",
        "task_requirements",
        ["task_id", "role_id"],
        unique=True,
        postgresql_where=sa.text("role_id IS NOT NULL"),
    )
    op.create_index(
        "uq_task_requirements_skill",
        "task_requirements",
        ["task_id", "skill_id"],
        unique=True,
        postgresql_where=sa.text("skill_id IS NOT NULL"),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("principal_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("finished_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed', 'cancelled')", name=op.f("ck_runs_status")
        ),
        sa.CheckConstraint("attempt >= 1", name=op.f("ck_runs_attempt_positive")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_runs_version_positive")),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["task_claims.id"], name=op.f("fk_runs_claim_id_task_claims")
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"], ["principals.id"], name=op.f("fk_runs_principal_id_principals")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_runs_session_id_sessions")
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_runs_task_id_tasks")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_runs_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("task_id", "attempt", name="uq_runs_task_attempt"),
    )
    op.create_index("ix_runs_claim", "runs", ["claim_id"], unique=False)
    op.create_index(
        "ix_runs_tenant_created", "runs", ["tenant_id", "created_at", "id"], unique=False
    )
    op.create_index(
        "uq_runs_one_running_per_task",
        "runs",
        ["task_id"],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("created_by_principal_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("uri", sa.Text(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_principal_id"],
            ["principals.id"],
            name=op.f("fk_artifacts_created_by_principal_id_principals"),
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_artifacts_run_id_runs")),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_artifacts_task_id_tasks")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_artifacts_tenant_id_tenants")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], name=op.f("fk_artifacts_workspace_id_workspaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    op.create_index("ix_artifacts_run", "artifacts", ["run_id"], unique=False)
    op.create_index("ix_artifacts_task", "artifacts", ["task_id"], unique=False)
    op.create_index(
        "ix_artifacts_tenant_created", "artifacts", ["tenant_id", "created_at", "id"], unique=False
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("artifact_id", sa.UUID(), nullable=True),
        sa.Column("requested_by_principal_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("required_role_id", sa.UUID(), nullable=True),
        sa.Column("assigned_principal_id", sa.UUID(), nullable=True),
        sa.Column("decision_by_principal_id", sa.UUID(), nullable=True),
        sa.Column("decision_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'cancelled')",
            name=op.f("ck_approvals_status"),
        ),
        sa.CheckConstraint(
            "num_nonnulls(required_role_id, assigned_principal_id) = 1",
            name=op.f("ck_approvals_one_addressing_mode"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_approvals_version_positive")),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["artifacts.id"], name=op.f("fk_approvals_artifact_id_artifacts")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_principal_id"],
            ["principals.id"],
            name=op.f("fk_approvals_assigned_principal_id_principals"),
        ),
        sa.ForeignKeyConstraint(
            ["decision_by_principal_id"],
            ["principals.id"],
            name=op.f("fk_approvals_decision_by_principal_id_principals"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_principal_id"],
            ["principals.id"],
            name=op.f("fk_approvals_requested_by_principal_id_principals"),
        ),
        sa.ForeignKeyConstraint(
            ["required_role_id"], ["roles.id"], name=op.f("fk_approvals_required_role_id_roles")
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_approvals_task_id_tasks")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_approvals_tenant_id_tenants")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], name=op.f("fk_approvals_workspace_id_workspaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(
        "ix_approvals_pending",
        "approvals",
        ["tenant_id", "status"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index("ix_approvals_task", "approvals", ["task_id"], unique=False)
    op.create_index(
        "ix_approvals_tenant_created", "approvals", ["tenant_id", "created_at", "id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_approvals_tenant_created", table_name="approvals")
    op.drop_index("ix_approvals_task", table_name="approvals")
    op.drop_index(
        "ix_approvals_pending",
        table_name="approvals",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("approvals")
    op.drop_index("ix_artifacts_tenant_created", table_name="artifacts")
    op.drop_index("ix_artifacts_task", table_name="artifacts")
    op.drop_index("ix_artifacts_run", table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(
        "uq_runs_one_running_per_task",
        table_name="runs",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index("ix_runs_tenant_created", table_name="runs")
    op.drop_index("ix_runs_claim", table_name="runs")
    op.drop_table("runs")
    op.drop_index(
        "uq_task_requirements_skill",
        table_name="task_requirements",
        postgresql_where=sa.text("skill_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_task_requirements_role",
        table_name="task_requirements",
        postgresql_where=sa.text("role_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_task_requirements_capability",
        table_name="task_requirements",
        postgresql_where=sa.text("capability_id IS NOT NULL"),
    )
    op.drop_index("ix_task_requirements_task", table_name="task_requirements")
    op.drop_table("task_requirements")
    op.drop_index("ix_task_relations_to", table_name="task_relations")
    op.drop_index("ix_task_relations_from", table_name="task_relations")
    op.drop_table("task_relations")

    # tasks leave the organization model only after task_relations is gone
    # (its composite FKs depend on uq_tasks_tenant_id_id).
    op.drop_constraint(op.f("fk_tasks_workspace_id_workspaces"), "tasks", type_="foreignkey")
    op.drop_constraint("uq_tasks_tenant_id_id", "tasks", type_="unique")
    op.drop_index("ix_tasks_workspace", table_name="tasks")
    op.drop_column("tasks", "workspace_id")
    op.drop_index(
        "uq_principal_roles_scoped",
        table_name="principal_roles",
        postgresql_where=sa.text("workspace_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_principal_roles_global",
        table_name="principal_roles",
        postgresql_where=sa.text("workspace_id IS NULL"),
    )
    op.drop_index("ix_principal_roles_role", table_name="principal_roles")
    op.drop_index("ix_principal_roles_principal", table_name="principal_roles")
    op.drop_table("principal_roles")
    op.drop_index("ix_workspace_members_principal", table_name="workspace_members")
    op.drop_table("workspace_members")
    op.drop_index(
        "uq_roles_workspace_slug",
        table_name="roles",
        postgresql_where=sa.text("workspace_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_roles_global_slug", table_name="roles", postgresql_where=sa.text("workspace_id IS NULL")
    )
    op.drop_index("ix_roles_tenant_created", table_name="roles")
    op.drop_table("roles")
    op.drop_index("ix_principal_skills_skill", table_name="principal_skills")
    op.drop_table("principal_skills")
    op.drop_index("ix_principal_capabilities_capability", table_name="principal_capabilities")
    op.drop_table("principal_capabilities")
    op.drop_index(
        "uq_workspaces_sibling_slug",
        table_name="workspaces",
        postgresql_where=sa.text("parent_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_workspaces_root_slug",
        table_name="workspaces",
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.drop_index("ix_workspaces_tenant_parent", table_name="workspaces")
    op.drop_index("ix_workspaces_tenant_created", table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index("ix_skills_tenant_created", table_name="skills")
    op.drop_table("skills")
    op.drop_index("ix_capabilities_tenant_created", table_name="capabilities")
    op.drop_table("capabilities")
    # ### end Alembic commands ###
